-- ==================================================================
-- P6 Structural Separation
--   Equipment.kind enum (5 hardcoded), RackModule, 4 category tables.
--   Drop MaterialCategory / Material / MaterialAlias entirely.
--   Cable becomes polymorphic with CHECK constraints.
-- DESTRUCTIVE: existing equipment/cables/fiber_paths data is wiped
-- (per user direction — Phase 1-5 Material* tree is incompatible with
-- the new model).
-- ==================================================================

-- ── Step 0: destructive data wipe (no compatible mapping exists) ──
DELETE FROM "cables";
DELETE FROM "fiber_paths";
DELETE FROM "ports";
DELETE FROM "equipment_photos";
DELETE FROM "maintenance_logs";
DELETE FROM "equipment";
DELETE FROM "material_aliases";
DELETE FROM "materials";
DELETE FROM "material_categories";

-- ── Step 1: enum + FK drops (autogenerated) ──
CREATE TYPE "EquipmentKind" AS ENUM ('RACK', 'OFD', 'DISTRIBUTION', 'GROUNDING', 'HVAC');

ALTER TABLE "cables" DROP CONSTRAINT IF EXISTS "cables_material_category_id_fkey";
ALTER TABLE "cables" DROP CONSTRAINT IF EXISTS "cables_material_id_fkey";
ALTER TABLE "equipment" DROP CONSTRAINT IF EXISTS "equipment_floor_id_fkey";
ALTER TABLE "equipment" DROP CONSTRAINT IF EXISTS "equipment_material_category_id_fkey";
ALTER TABLE "equipment" DROP CONSTRAINT IF EXISTS "equipment_material_id_fkey";
ALTER TABLE "equipment" DROP CONSTRAINT IF EXISTS "equipment_parent_equipment_id_fkey";
ALTER TABLE "material_aliases" DROP CONSTRAINT IF EXISTS "material_aliases_category_id_fkey";
ALTER TABLE "material_categories" DROP CONSTRAINT IF EXISTS "material_categories_parent_id_fkey";
ALTER TABLE "materials" DROP CONSTRAINT IF EXISTS "materials_category_id_fkey";

-- ── Step 2: cables — drop legacy FKs/cols, add new polymorphic cols ──
ALTER TABLE "cables"
  DROP COLUMN "material_category_id",
  DROP COLUMN "material_id",
  ADD COLUMN  "category_id" TEXT,
  ADD COLUMN  "source_module_id" TEXT,
  ADD COLUMN  "target_module_id" TEXT,
  ALTER COLUMN "source_equipment_id" DROP NOT NULL,
  ALTER COLUMN "target_equipment_id" DROP NOT NULL;

-- ── Step 3: equipment — drop legacy fields, add kind/properties ──
ALTER TABLE "equipment"
  DROP COLUMN "height_u",
  DROP COLUMN "manufacturer",
  DROP COLUMN "material_category_id",
  DROP COLUMN "material_id",
  DROP COLUMN "model",
  DROP COLUMN "parent_equipment_id",
  DROP COLUMN "serial_number",
  DROP COLUMN "spec_params",
  DROP COLUMN "start_u",
  ADD COLUMN  "kind" "EquipmentKind" NOT NULL,
  ALTER COLUMN "floor_id" SET NOT NULL,
  ALTER COLUMN "position_x_2d" SET NOT NULL,
  ALTER COLUMN "position_y_2d" SET NOT NULL,
  ALTER COLUMN "width_2d" SET NOT NULL,
  ALTER COLUMN "height_2d" SET NOT NULL,
  ALTER COLUMN "rotation" SET NOT NULL;

-- ── Step 4: drop deprecated tables/enums ──
DROP TABLE "material_aliases";
DROP TABLE "materials";
DROP TABLE "material_categories";
DROP TYPE "MaterialCategoryType";

-- ── Step 5: new tables ──
CREATE TABLE "rack_modules" (
    "id" TEXT NOT NULL,
    "rack_equipment_id" TEXT NOT NULL,
    "category_id" TEXT NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "start_u" INTEGER NOT NULL,
    "height_u" INTEGER NOT NULL,
    "install_date" DATE,
    "manager" VARCHAR(100),
    "description" TEXT,
    "properties" JSONB,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "created_by" TEXT,
    "updated_by" TEXT,
    CONSTRAINT "rack_modules_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "rack_module_categories" (
    "id" TEXT NOT NULL,
    "code" VARCHAR(30) NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "description" TEXT,
    "display_color" VARCHAR(7),
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "rack_module_categories_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "rack_presets" (
    "id" TEXT NOT NULL,
    "code" VARCHAR(30) NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "total_u" INTEGER NOT NULL,
    "canvas_width" DOUBLE PRECISION NOT NULL,
    "canvas_height" DOUBLE PRECISION NOT NULL,
    "modules" JSONB NOT NULL,
    "description" TEXT,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "created_by" TEXT,
    "updated_by" TEXT,
    CONSTRAINT "rack_presets_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "cable_categories" (
    "id" TEXT NOT NULL,
    "code" VARCHAR(30) NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "description" TEXT,
    "display_color" VARCHAR(7),
    "display_group" VARCHAR(20),
    "icon_name" VARCHAR(30),
    "unit" VARCHAR(20),
    "spec_template" JSONB,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "cable_categories_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "bom_materials" (
    "id" TEXT NOT NULL,
    "code" VARCHAR(30) NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "parent_id" TEXT,
    "description" TEXT,
    "icon_name" VARCHAR(30),
    "unit" VARCHAR(20),
    "spec_template" JSONB,
    "display_color" VARCHAR(7),
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "bom_materials_pkey" PRIMARY KEY ("id")
);

-- ── Step 6: indexes ──
CREATE UNIQUE INDEX "rack_module_categories_code_key" ON "rack_module_categories"("code");
CREATE UNIQUE INDEX "rack_presets_code_key" ON "rack_presets"("code");
CREATE UNIQUE INDEX "cable_categories_code_key" ON "cable_categories"("code");
CREATE UNIQUE INDEX "bom_materials_code_key" ON "bom_materials"("code");

-- ── Step 7: foreign keys ──
ALTER TABLE "equipment"
  ADD CONSTRAINT "equipment_floor_id_fkey" FOREIGN KEY ("floor_id")
    REFERENCES "floors"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "rack_modules"
  ADD CONSTRAINT "rack_modules_rack_equipment_id_fkey" FOREIGN KEY ("rack_equipment_id")
    REFERENCES "equipment"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "rack_modules"
  ADD CONSTRAINT "rack_modules_category_id_fkey" FOREIGN KEY ("category_id")
    REFERENCES "rack_module_categories"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "rack_modules"
  ADD CONSTRAINT "rack_modules_created_by_fkey" FOREIGN KEY ("created_by")
    REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "rack_modules"
  ADD CONSTRAINT "rack_modules_updated_by_fkey" FOREIGN KEY ("updated_by")
    REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "rack_presets"
  ADD CONSTRAINT "rack_presets_created_by_fkey" FOREIGN KEY ("created_by")
    REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "rack_presets"
  ADD CONSTRAINT "rack_presets_updated_by_fkey" FOREIGN KEY ("updated_by")
    REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "bom_materials"
  ADD CONSTRAINT "bom_materials_parent_id_fkey" FOREIGN KEY ("parent_id")
    REFERENCES "bom_materials"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "cables"
  ADD CONSTRAINT "cables_source_module_id_fkey" FOREIGN KEY ("source_module_id")
    REFERENCES "rack_modules"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "cables"
  ADD CONSTRAINT "cables_target_module_id_fkey" FOREIGN KEY ("target_module_id")
    REFERENCES "rack_modules"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "cables"
  ADD CONSTRAINT "cables_category_id_fkey" FOREIGN KEY ("category_id")
    REFERENCES "cable_categories"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ── Step 8: polymorphic CHECK constraints ──
-- Each cable side must have exactly one endpoint (Equipment xor RackModule).
ALTER TABLE "cables" ADD CONSTRAINT "cable_source_one_of" CHECK (
  (source_equipment_id IS NOT NULL AND source_module_id IS NULL) OR
  (source_equipment_id IS NULL AND source_module_id IS NOT NULL)
);
ALTER TABLE "cables" ADD CONSTRAINT "cable_target_one_of" CHECK (
  (target_equipment_id IS NOT NULL AND target_module_id IS NULL) OR
  (target_equipment_id IS NULL AND target_module_id IS NOT NULL)
);
